### ISSUE TITLE
Fix birbmap explorer (clean up to single data source)

### ISSUE THREAD

**Issue by matth79** [calacademy-research/COMB#16]

**Comment by matth79** [comment]
Data Studio "explorations" are not meant to be shared but only for their creator to later publish to a report.

...such as [Caples Bird Counts](https://datastudio.google.com/c/reporting/8495dcff-77c5-4a42-812e-7ae5ed79494c/page/sFToC)

...which has now corrected the indexing bug and always omits UNKN.

**Comment by ddkapan** [comment]
Nice, the studio viewer could have the point number among other pop-up data, meanwhile the data look quite reasonable, but there are large between year changes which I am not surprised by... in the long-run *raw* and *occupancy* estimates could be plotted for acoustic, human and one, the other or both for the two categories respectively... A veeeeerrryyy loooong stretch goal would be to play the relevant sounds from a pop-up!
