### ISSUE TITLE
Productionize delintPC.R

### ISSUE THREAD

**Issue by matth79** [calacademy-research/COMB#17]
- DRY refactor (duplicate version to call the other)
- (script  already written [~/COMB/point_counts/data-ingest/src/delintPC.R] - just needs to be executed and maybe some troubleshooting)

**Comment by mkclapp** [comment]
ran delintPC.R, added necessary R packages and dependencies. Created a csv of delinted data (PC_delinted.csv) and added to point_counts/data_ingest/output for use in COMB/models scripts.
