### ISSUE TITLE
What channel will authors use for high-level feedback?

### ISSUE THREAD

**Issue by matth79** [calacademy-research/COMB#2]
Pull requests are a good mechanism for discussing specific edits already made, but in cases where we want to share high-level feedback with many or all code contributors, where shall we do that?

GitHub issues?
Private chat.google.com space?
Wait for regular video calls?

(This here is my vote for GitHub issues, acknowledging that those are publicly viewable.)

**Comment by ddkapan** [comment]
This sounds great for a spot to point out medium and large issues. For lot’s of back-and-forth we’ve been using Slack, yet Google chat is also fine! Thoughts everyone?

**Comment by matth79** [comment]
Sounds good to me. I will close this and use issues.
