### ISSUE TITLE
Branches and pull requests

### ISSUE THREAD

**Issue by ddkapan** [calacademy-research/COMB#3]
Hi all, let's follow @matth79 and use [branches](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches#working-with-branches) and [pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) to move forward. See the links for more information. SO for instance, if I want to add a new feature (say point counts) I can create a 'point_count' branch and work on that branch by myself. Then when I'm happy with it I can create a pull request and then it can be looked over and approved (right now we all have equal privileges so I could approve my own pull request, but Matt suggests ultimately having one person in this role.  So let's try this out and if we are having issues, we can discuss them here.  Best, Durrell

**Comment by foozleface** [comment]
Hi everyone,
  
  Git, like wizards of yore, is subtle and quick to anger. If you get stuck, feel free to be in touch. It's a steep learning curve.

-Joe

**Comment by ddkapan** [comment]
Not very active, so people got the message, see the next issue where I document forking and cloning the repo locally and then using git subtree to get features from one repo to another...
