### ISSUE TITLE
readPC / delintPC CSV filename depends on date

### ISSUE THREAD

**Issue by matth79** [calacademy-research/COMB#31]
Currently delintPC has a hard-coded filename that includes the date readPC ran, but this is not stable in the case that someone has re-run readPC.

**Comment by mkclapp** [comment]
Bookmarking this to address on Tuesday 3/29!

**Comment by ddkapan** [comment]
Maybe give a stable name to the object as written and we can work with @mschulist  to rename the old object with the creation date embedded.  That will give us a nice function to do so for model runs etc saved to Google drive.

**Comment by matth79** [comment]
Stable filenames sure make things easier.

One thing to consider is that Google Drive can have multiple versions of the same object. It might be worth investigating how that interacts with drive_upload. If the upload just appends the latest version, keeping the history, then custom renaming and copy strategies may not be needed.

**Comment by mkclapp** [comment]
Addressed in recent pull request #75
