### ISSUE TITLE
Replace /acoustic/…/output/‘dataML*.csv’ with newly computed versions 

### ISSUE THREAD

**Issue by ddkapan** [calacademy-research/COMB#33]
See pull request (approved) “ updated readML.R to include some code from Mark. We will need to replace the files previously placed in the Google drive with the new dataML versions.”

**Comment by mschulist** [comment]
Is it point_count/... or acoustic/data_ingest/... ?

**Comment by ddkapan** [comment]
Yup, you got it right!

**Comment by ddkapan** [comment]
Look on google drive, I think Jack may have done this.  Work backwards from the latest code in models to see what is referenced. Cheers.

**Comment by mschulist** [comment]
Yeah, while I recreating the versions I noticed that Jack had put new ones in there.

**Comment by ddkapan** [comment]
Look over Jack's new code as well. You can 'codify' (ha, ha) the changes by ensuring that the different cutoffs are documented (and possibly commented out) so we know what generated what. Thanks! :)

**Comment by mschulist** [comment]
I believe that Jack replaced them all with the new versions, so I believe that it should be closed.

**Comment by ddkapan** [comment]
See discussion on slack, Jack suggested dropping the precomputed slices and that will be consistent with doing some of the filtering steps on the fly. See issue #

**Comment by ddkapan** [comment]
@mschulist is this issue now concluded?

**Comment by mschulist** [comment]
Yes. They should all be the correct versions in google drive now.
