### ISSUE TITLE
Merge pull request order for hard work by @matt79 over weekend

### ISSUE THREAD

**Issue by ddkapan** [calacademy-research/COMB#48]
Hi all, thank you all again for your amazing effort last week!

@matth79 worked all day Saturday and some on Sunday on the combined model and other issues: package environment and adopting consistent styles. Thanks Matt!!!

Once everyone has looked at the changes it may be good to merge them in a particular order, mostly oldest -> newest. So I can do that a little later today. Let me know when you are finished reviewing @mkclapp & @jdumbacher!

**Comment by mkclapp** [comment]
I think aside from the renv request, all these changes have been successfully merged onto main! Thanks @matth79 !!

**Comment by ddkapan** [comment]
We figured it out and also merged renv, closing this issue. Thanks again @matth79 !!!!!
