### ISSUE TITLE
data plumbing (mostly get @mkclapp's computer to use drive_sync)

### ISSUE THREAD

**Issue by ddkapan** [calacademy-research/COMB#51]

**Comment by matth79** [comment]
Is this one obsolete?

(especially since issue #26 appears to be a broader near-duplicate)

**Comment by matth79** [comment]
Mary and I diagnosed:

stale version of the googledrive package on Mary's laptop had a bug accessing team drives.

Upgrading the package one-off fixed it, and Mary's running renv::restore for good measure.

**Comment by ddkapan** [comment]
Awesome news! Thanks!
