### ISSUE TITLE
Remove score subsampling from combined.R

### ISSUE THREAD

**Issue by matth79** [calacademy-research/COMB#60]
Short story: code as of end-of-hackathon was correct.

(@mkclapp had that right on even earlier days.)

@sdenton4 convinced @matth79 in a video call that the "scores", of which we have nsamples many, really were assumed by AHM 7.6.3 to have been in one-to-one correspondence with the "1s" summed up to get the entries or y.aru. (Sufficient but not necessary for nsamples = sum(matrix entries of y.aru) === sum(ARU counts))

Therefore, we should remove the subsampling.

**Comment by mkclapp** [comment]
I just addressed this (and potentially beat this dead horse) in an email to all collabs in response to your recent notebook share, with additional thoughts on the ramifications of thresholding/subsampling etc, based on my conversations with you and Tom!
