### ISSUE TITLE
Fix .gitignore that was updated in recent pull request, we still need to ignore /input/

### ISSUE THREAD

**Issue by ddkapan** [calacademy-research/COMB#72]
Not sure what happened, probably during one of our commits, but we need to still generically ignore `/input/` directories, or else we will pull in a lot of files from your local directories and push them to GitHub.  No Bueno.   Don't pull various branches (I've temporarily patched the 'main' branch .gitignore). I'm tagging everyone actively developing so they read this message. Meaning @mkclapp @laurenharrell @matth79 @mschulist & @jdumbacher, I'll update the issue status and fix here.

**Comment by ddkapan** [comment]
Ok, I figured it out. @matth79 suggested we DO NOT ignore generically `input` since we may want to synchronize symlinks. So the `input` directory was removed from the `.gitignore` and some specific `input` directories were left in `.gitignore`. This wasn't a problem until we added new chunks with original inputs in new places that were not `.gitignored`.  We can either go back to generically ignoring all inputs and specifically unignoring those we want to synchronize (e.g. symlink inputs) or something else. Thoughts everyone? @mkclapp @laurenharrell @matth79 @mschulist & @jdumbacher.

**Comment by mschulist** [comment]
If the symlinks contain absolute paths, then synchronizing them would make them not work on other people's computers.

**Comment by ddkapan** [comment]
Totally true, I think @matth79 had a workaround but I don't recall the details. We should test if the the symlinks work for all users and in the meantime we may want to adjust the `.gitignore` to be specific to various input directories.

**Comment by ddkapan** [comment]
I'm going to CLOSE this issue which I provisionally fixed. I have a working .gitignore on the main branch that ignores /input and /output which facilitates starting at an intermediate spot in the code and using arbitrary inputs from previous outputs created by someone else and synchronized to google drive to continue work.
