### ISSUE TITLE
skeleton code for posterior predictive checks

### ISSUE THREAD

**Issue by mkclapp** [calacademy-research/COMB#79]
The following code can be added to the end of 'combined.R' to begin working on PPCs for the models. This was originally developed with Lauren and needs to be run and debugged...

# attach(jagsResult_WEWP$sims.list)
nIter <- length(jagsResult_WEWP$sims.list$p11)
Tobs <- numeric(nIter)
Tsim <- numeric(nIter)
n <- rowSums(!is.na(data$y.ind[, 1:4])) # n = number of visits
y <- rowSums(data$y.ind[, 1:4], na.rm = TRUE)
for (iter in 1:nIter) {
  Tobs[iter] <- sum((sqrt(y) - sqrt((jagsResult_WEWP$sims.list$z[iter, ] * jagsResult_WEWP$sims.list$p11[iter] + (1 - jagsResult_WEWP$sims.list$z[iter, ]) * jagsResult_WEWP$sims.list$p10[iter]) * n))^2)
  ySim <- rbinom(84, n, jagsResult_WEWP$sims.list$z[iter, ] * jagsResult_WEWP$sims.list$p11[iter] + (1 - jagsResult_WEWP$sims.list$z[iter, ]) * jagsResult_WEWP$sims.list$p10[iter])
  Tsim[iter] <- sum((sqrt(ySim) - sqrt((jagsResult_WEWP$sims.list$z[iter, ] * jagsResult_WEWP$sims.list$p11[iter] + (1 - jagsResult_WEWP$sims.list$z[iter, ]) * jagsResult_WEWP$sims.list$p10[iter]) * n))^2)
}
# detach(jagsResult_WEWP$sims.list)

MASS::eqscplot(Tobs, Tsim,
  xlim = range(Tobs, Tsim), ylim = range(Tobs, Tsim),
  xlab = "Observed data", ylab = "Simulated data"
)
abline(0, 1, lwd = 2, col = "red")
mean(Tsim > Tobs) # the P value

hist(Tsim, breaks = 50)
hist(Tobs, breaks = 50)

**Comment by ddkapan** [comment]
I think you have this working on your branch, can you ping me to discuss merging that branch @mkclapp?

**Comment by mkclapp** [comment]
Yes; I can start a new issue with only that change to combined.R and do a pull request to incorporate it. Or, I can make it a standalone script that reads in JAGS output.

**Comment by ddkapan** [comment]
I think we settled on a standalone but not totally sure. Was busy last week & today! Let's review tomorrow!
